version: '3.8'

services:
  seller-bot:
    restart: always
    image: buguzei/seller-bot:seller-bot
    env_file:
      - ./.env
    volumes:
      - ./config/:/root/config/
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
  postgres:
    restart: always
    env_file:
      - ./.env
    image: buguzei/seller-bot:postgres
    ports:
      - '5436:5432'
  redis:
    restart: always
    image: redis:latest
    command: --port 6380
    ports:
      - '6380:6380'
