name: SellerBot

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_HUB_ID: 'buguzei'
  DOCKER_HUB_REPO: 'seller-bot'
  IMAGE_NAME: 'seller-bot'
  CONTAINER_NAME: 'app_seller-bot_1'
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: go test -v ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login --username=$DOCKER_HUB_ID --password=$DOCKER_HUB_PASS

      - name: Build image
        run: docker build -t $DOCKER_HUB_ID/$DOCKER_HUB_REPO:$IMAGE_NAME .

      - name: Push image to Docker Hub
        run: docker push $DOCKER_HUB_ID/$DOCKER_HUB_REPO:$IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push


    steps:
      - name: Deploy new docker image to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DOCKER_HUB_PASS, CONTAINER_NAME, IMAGE_NAME, DOCKER_HUB_ID, DOCKER_HUB_REPO
          script: |
            # Changing directory to app            
            cd app
            
            docker-compose pull
            
            # Pulling new image and then starting app in background
            docker-compose up -d